name: 'gcloud setup'
description: 'gcloud setup'

inputs:
  project_id:
    description: 'literal project identifier'
    required: true

  project_number:
    description: 'numberic project identifier, used in workload_identity_provider'
    required: true

  region:
    description: ''
    required: true

  workload_identity_provider:
    description: ''
    required: true

runs:
  using: "composite"
  steps:          
      # Authenticate to the Google Cloud platform using Workload Identity Federation, the most secure and preferred
      # way to connect to our Google Cloud Platform from GitHub.
      # The workload_identity_provider is managed for the entire cluster and you don't need to worry about it.
      # The service_account must be setup within your Google Project. 
      - id: auth
        name: Authenticate to Google using WIF
        uses: google-github-actions/auth@v0
        with:
          # workload_identity_provider is configured in GCP console Workload Identity Pools
          # projects/<PROJECT_NUMBER>/locations/global/workloadIdentityPools/workload-pool/providers/workload-gh-provider
          workload_identity_provider: projects/${{ inputs.project_number }}/locations/global/workloadIdentityPools/workload-gh-pool/providers/workload-gh-provider
          service_account:  'cicd-service-account@${{ inputs.project_id }}.iam.gserviceaccount.com'
          project_id:  ${{ inputs.project_id }} 
          token_format: 'access_token'

                
      # The GCloud CLI must be installed and configured in the container to enable subsequent steps
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ inputs.project_id }} 
          install_components: 'beta,skaffold'
      
      # Configure docker authorization for access to the Google Artifact Registry
      - name: Configure Docker
        shell: bash
        run: |-
          gcloud --quiet auth configure-docker ${{ inputs.region }}-docker.pkg.dev


