name: 'deploy-docs'
description: 'deploy docs to google cloud storage'

inputs:
  project_id:
    description: 'GCP project id of which executes the action'
    required: true

  project_number:
    description: 'numberic project identifier, used in workload_identity_provider'
    required: true

  region:
    description: ''
    required: true

  bucket:
    description: 'target bucket it is supposed to be the same as project_id, will be created if missing'
    required: true

  prefix:
    description: 'prefix to add to each doc'
    required: true

  vistor_projects:
    description: 'comma separated project_ids being granted read only access'
    required: true
    
runs:
  using: "composite"
  steps:          
    - name: "gcloud-setup"
      uses: NativeVoice/gh_actions/setup-gcloud@develop
      with:
        project_id: ${{ inputs.project_id }}
        project_number: ${{ inputs.project_number }}
        region: ${{ inputs.region }}

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: deploy
      shell: bash
      run: |
        set -e -x
        pip install mkdocs mkdocs-material mkdocs-minify-plugin mkdocs-git-revision-date-localized-plugin mkdocs-awesome-pages-plugin
        python3 -m mkdocs build
        rm -rf node_modules
        npm i --force
        ls -l
        cd site
        gsutil ls ${{ inputs.bucket }} \
          || gcloud storage buckets create ${{ inputs.bucket }} --location=${{ inputs.region}}
        gsutil cp -r * ${{ inputs.bucket }}/${{ inputs.prefix }}

        for project_id in $(echo "${{ inputs.vistor_projects }}" | cut -d "," -f1,2 --output-delimiter=" "); do
          gsutil iam ch serviceAccount:gsa-nv-service-sa@${project_id}.iam.gserviceaccount.com:roles/storage.admin ${{ inputs.bucket }}
        done
